name: Build and Release

on:
  push:
    paths:
      - 'scr/join/main.js'
  pull_request:
    paths:
      - 'scr/join/main.js'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build to EXE
        run: |
          pkg scr\join\main.js --compress GZip -t node18-win

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: AutoBuildExe
          release_name: AutoBuildExe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload main.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main.exe
          asset_name: main.exe
          asset_content_type: application/octet-stream
